import { AiRole } from './enums';
import { MenuItem, RestaurantSummary } from './entities';

/**
 * Rich UI payload the AI response can carry alongside its text so the
 * client can render restaurant/menu cards instead of plain prose.
 */
export interface AiRichContent {
  restaurants?: RestaurantSummary[];
  menuItems?: MenuItem[];
  suggestedPrompts?: string[];
}

export interface AiMessage {
  id: string;
  role: AiRole;
  content: string;
  rich?: AiRichContent;
  createdAt: string;
}

export interface AiConversation {
  id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  messages: AiMessage[];
}

export interface AiChatRequest {
  conversationId?: string;
  message: string;
  context?: {
    lat?: number;
    lng?: number;
    restaurantId?: string;
  };
}

export interface AiChatResponse {
  conversationId: string;
  message: AiMessage;
  /** True when the response was generated by the local fallback provider
   *  (no AI_API_KEY configured) rather than a real LLM call. */
  degraded: boolean;
}

/** Names of the whitelisted server-side tools the AI tool router exposes.
 *  The LLM never queries the database directly — every fact it can state
 *  about a restaurant must come back through one of these. */
export enum AiToolName {
  SEARCH_RESTAURANTS = 'searchRestaurants',
  FIND_NEARBY_RESTAURANTS = 'findNearbyRestaurants',
  GET_RESTAURANT = 'getRestaurant',
  GET_MENU = 'getMenu',
  SEARCH_DISHES = 'searchDishes',
  GET_REVIEWS = 'getReviews',
  GET_OPENING_HOURS = 'getOpeningHours',
  GET_USER_PREFERENCES = 'getUserPreferences',
}
