import { addIcons } from 'ionicons';
import {
  addOutline,
  americanFootballOutline,
  arrowBack,
  bookmarkOutline,
  cafeOutline,
  calendarOutline,
  callOutline,
  cameraOutline,
  chatbubbleEllipsesOutline,
  checkmarkCircle,
  chevronForward,
  closeCircle,
  closeOutline,
  compassOutline,
  ellipsisHorizontal,
  filterOutline,
  flagOutline,
  flameOutline,
  heart,
  heartOutline,
  homeOutline,
  informationCircleOutline,
  leafOutline,
  locateOutline,
  locationOutline,
  logOutOutline,
  mailOutline,
  mapOutline,
  navigateOutline,
  notificationsOutline,
  optionsOutline,
  pencilOutline,
  personCircleOutline,
  personOutline,
  pizzaOutline,
  restaurantOutline,
  searchOutline,
  sendOutline,
  shareOutline,
  sparkles,
  star,
  starOutline,
  storefrontOutline,
  thumbsDownOutline,
  thumbsUpOutline,
  timeOutline,
  trashOutline,
  wifiOutline,
} from 'ionicons/icons';

/** Registers every icon name used anywhere in the app, once, at startup —
 *  Ionic's standalone `ion-icon` needs each icon explicitly registered. */
export function registerIcons(): void {
  addIcons({
    'add-outline': addOutline,
    'american-football-outline': americanFootballOutline,
    'arrow-back': arrowBack,
    'bookmark-outline': bookmarkOutline,
    'cafe-outline': cafeOutline,
    'calendar-outline': calendarOutline,
    'call-outline': callOutline,
    'camera-outline': cameraOutline,
    'chatbubble-ellipses-outline': chatbubbleEllipsesOutline,
    'checkmark-circle': checkmarkCircle,
    'chevron-forward': chevronForward,
    'close-circle': closeCircle,
    'close-outline': closeOutline,
    'compass-outline': compassOutline,
    'ellipsis-horizontal': ellipsisHorizontal,
    'filter-outline': filterOutline,
    'flag-outline': flagOutline,
    'flame-outline': flameOutline,
    heart,
    'heart-outline': heartOutline,
    'home-outline': homeOutline,
    'information-circle-outline': informationCircleOutline,
    'leaf-outline': leafOutline,
    'locate-outline': locateOutline,
    'location-outline': locationOutline,
    'log-out-outline': logOutOutline,
    'mail-outline': mailOutline,
    'map-outline': mapOutline,
    'navigate-outline': navigateOutline,
    'notifications-outline': notificationsOutline,
    'options-outline': optionsOutline,
    'pencil-outline': pencilOutline,
    'person-circle-outline': personCircleOutline,
    'person-outline': personOutline,
    'pizza-outline': pizzaOutline,
    'restaurant-outline': restaurantOutline,
    'search-outline': searchOutline,
    'send-outline': sendOutline,
    'share-outline': shareOutline,
    sparkles,
    star,
    'star-outline': starOutline,
    'storefront-outline': storefrontOutline,
    'thumbs-down-outline': thumbsDownOutline,
    'thumbs-up-outline': thumbsUpOutline,
    'time-outline': timeOutline,
    'trash-outline': trashOutline,
    'wifi-outline': wifiOutline,
  });
}
