/** Stable machine-readable error codes returned in the `error.code` field. */
export enum ErrorCode {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',

  RESTAURANT_NOT_FOUND = 'RESTAURANT_NOT_FOUND',
  MENU_ITEM_NOT_FOUND = 'MENU_ITEM_NOT_FOUND',

  REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_EXISTS = 'REVIEW_ALREADY_EXISTS',
  REVIEW_RATE_LIMITED = 'REVIEW_RATE_LIMITED',
  REVIEW_REJECTED = 'REVIEW_REJECTED',

  FAVORITE_ALREADY_EXISTS = 'FAVORITE_ALREADY_EXISTS',
  FAVORITE_NOT_FOUND = 'FAVORITE_NOT_FOUND',

  AI_TOOL_NOT_ALLOWED = 'AI_TOOL_NOT_ALLOWED',
  AI_PROVIDER_ERROR = 'AI_PROVIDER_ERROR',
}
