// Static reference data for the DineScout demo seed. Singapore is the
// initial demo location per the product brief.

export const CUISINES: { slug: string; name: string; emoji: string }[] = [
  { slug: 'indian', name: 'Indian', emoji: '🍛' },
  { slug: 'chinese', name: 'Chinese', emoji: '🥡' },
  { slug: 'japanese', name: 'Japanese', emoji: '🍣' },
  { slug: 'korean', name: 'Korean', emoji: '🍲' },
  { slug: 'thai', name: 'Thai', emoji: '🍜' },
  { slug: 'vietnamese', name: 'Vietnamese', emoji: '🍲' },
  { slug: 'italian', name: 'Italian', emoji: '🍝' },
  { slug: 'mexican', name: 'Mexican', emoji: '🌮' },
  { slug: 'american', name: 'American', emoji: '🍔' },
  { slug: 'mediterranean', name: 'Mediterranean', emoji: '🥙' },
  { slug: 'arabic', name: 'Arabic', emoji: '🧆' },
  { slug: 'singaporean', name: 'Singaporean', emoji: '🇸🇬' },
  { slug: 'malaysian', name: 'Malaysian', emoji: '🍢' },
  { slug: 'fusion', name: 'Fusion', emoji: '🍱' },
  { slug: 'pizza', name: 'Pizza', emoji: '🍕' },
  { slug: 'burger', name: 'Burger', emoji: '🍔' },
  { slug: 'cafe', name: 'Cafe', emoji: '☕' },
  { slug: 'dessert', name: 'Dessert', emoji: '🍰' },
];

export const DIETARY_OPTIONS: { slug: string; label: string; emoji: string }[] = [
  { slug: 'vegetarian', label: 'Veg', emoji: '🥬' },
  { slug: 'non_vegetarian', label: 'Non-Veg', emoji: '🍗' },
  { slug: 'vegan', label: 'Vegan', emoji: '🌱' },
  { slug: 'halal', label: 'Halal', emoji: '☪️' },
  { slug: 'jain', label: 'Jain', emoji: '🙏' },
  { slug: 'seafood', label: 'Seafood', emoji: '🦐' },
];

export const NEIGHBORHOODS: { name: string; lat: number; lng: number }[] = [
  { name: 'Tanjong Pagar', lat: 1.2762, lng: 103.8455 },
  { name: 'Tiong Bahru', lat: 1.2857, lng: 103.827 },
  { name: 'Orchard', lat: 1.3048, lng: 103.8318 },
  { name: 'Bugis', lat: 1.3006, lng: 103.8559 },
  { name: 'Chinatown', lat: 1.2831, lng: 103.8443 },
  { name: 'Little India', lat: 1.3067, lng: 103.8517 },
  { name: 'Kampong Glam', lat: 1.302, lng: 103.8592 },
  { name: 'Clarke Quay', lat: 1.2906, lng: 103.8467 },
  { name: 'Holland Village', lat: 1.3116, lng: 103.7963 },
  { name: 'Katong', lat: 1.3037, lng: 103.9 },
  { name: 'Jurong East', lat: 1.3329, lng: 103.7436 },
  { name: 'Punggol', lat: 1.4043, lng: 103.9021 },
  { name: 'Tampines', lat: 1.3496, lng: 103.9568 },
  { name: 'Novena', lat: 1.3204, lng: 103.8437 },
  { name: 'Sentosa', lat: 1.2494, lng: 103.8303 },
  { name: 'Woodlands', lat: 1.4382, lng: 103.789 },
  { name: 'Bishan', lat: 1.3508, lng: 103.8486 },
  { name: 'East Coast', lat: 1.3016, lng: 103.9125 },
];

export const NAME_PREFIXES = [
  'The Golden', 'Spice', 'Little', 'Urban', 'Blue', 'Rustic', 'Coastal',
  'Marina', 'Heritage', 'Sunny', 'Lotus', 'Copper', 'Cloud', 'Garden',
  'Old Town', 'Red Lantern', 'Silver', 'Riverside',
];

export const NAME_SUFFIXES = [
  'Kitchen', 'House', 'Table', 'Bistro', 'Corner', 'Diner', 'Eatery',
  'Grill', 'Pot', 'Café', 'Bar & Kitchen', 'Kopitiam', 'Deli',
];

/** Per-cuisine dish pools. Each dish carries the menu category it belongs
 *  under, so generated menus have realistic category structure. */
export const DISH_POOLS: Record<
  string,
  { name: string; category: string; price: number; veg?: boolean; vegan?: boolean; spicy?: boolean }[]
> = {
  indian: [
    { name: 'Chicken Tikka Masala', category: 'Main Course', price: 16.9, spicy: true },
    { name: 'Paneer Butter Masala', category: 'Main Course', price: 14.5, veg: true },
    { name: 'Chana Masala', category: 'Main Course', price: 12.9, veg: true, vegan: true },
    { name: 'Chicken Biryani', category: 'Rice', price: 15.9, spicy: true },
    { name: 'Vegetable Biryani', category: 'Rice', price: 13.9, veg: true },
    { name: 'Garlic Naan', category: 'Bread', price: 4.5, veg: true },
    { name: 'Butter Naan', category: 'Bread', price: 4.5, veg: true },
    { name: 'Samosa (2pc)', category: 'Starters', price: 5.9, veg: true },
    { name: 'Onion Bhaji', category: 'Starters', price: 6.5, veg: true, vegan: true },
    { name: 'Mango Lassi', category: 'Drinks', price: 5.5, veg: true },
    { name: 'Gulab Jamun', category: 'Desserts', price: 5.9, veg: true },
  ],
  chinese: [
    { name: 'Kung Pao Chicken', category: 'Main Course', price: 15.9, spicy: true },
    { name: 'Mapo Tofu', category: 'Main Course', price: 12.9, veg: true, spicy: true },
    { name: 'Sweet and Sour Pork', category: 'Main Course', price: 16.5 },
    { name: 'Yangzhou Fried Rice', category: 'Rice', price: 11.9 },
    { name: 'Steamed Rice', category: 'Rice', price: 2.5, veg: true, vegan: true },
    { name: 'Xiao Long Bao (6pc)', category: 'Starters', price: 8.9 },
    { name: 'Spring Rolls (4pc)', category: 'Starters', price: 6.9, veg: true },
    { name: 'Wonton Noodle Soup', category: 'Popular', price: 9.9 },
    { name: 'Chinese Tea', category: 'Drinks', price: 2.5, veg: true, vegan: true },
    { name: 'Mango Pudding', category: 'Desserts', price: 5.5, veg: true },
  ],
  japanese: [
    { name: 'Salmon Nigiri (4pc)', category: 'Popular', price: 12.9 },
    { name: 'California Roll', category: 'Popular', price: 10.9 },
    { name: 'Chicken Katsu Curry', category: 'Main Course', price: 15.9 },
    { name: 'Tonkotsu Ramen', category: 'Main Course', price: 16.9 },
    { name: 'Miso Soup', category: 'Starters', price: 4.9, veg: true },
    { name: 'Gyoza (5pc)', category: 'Starters', price: 7.9 },
    { name: 'Unagi Don', category: 'Rice', price: 18.9 },
    { name: 'Edamame', category: 'Starters', price: 5.5, veg: true, vegan: true },
    { name: 'Green Tea', category: 'Drinks', price: 3.5, veg: true, vegan: true },
    { name: 'Matcha Ice Cream', category: 'Desserts', price: 6.5, veg: true },
  ],
  korean: [
    { name: 'Bibimbap', category: 'Rice', price: 14.9, veg: true },
    { name: 'Kimchi Jjigae', category: 'Main Course', price: 13.9, spicy: true },
    { name: 'Korean Fried Chicken', category: 'Popular', price: 17.9, spicy: true },
    { name: 'Bulgogi', category: 'Main Course', price: 18.9 },
    { name: 'Kimchi Pancake', category: 'Starters', price: 9.9, veg: true },
    { name: 'Tteokbokki', category: 'Starters', price: 8.9, veg: true, spicy: true },
    { name: 'Korean Barley Tea', category: 'Drinks', price: 3.5, veg: true, vegan: true },
    { name: 'Bingsu', category: 'Desserts', price: 9.9, veg: true },
  ],
  thai: [
    { name: 'Pad Thai', category: 'Popular', price: 12.9 },
    { name: 'Green Curry Chicken', category: 'Main Course', price: 14.9, spicy: true },
    { name: 'Tom Yum Soup', category: 'Starters', price: 8.9, spicy: true },
    { name: 'Som Tum Salad', category: 'Starters', price: 8.5, veg: true, spicy: true },
    { name: 'Thai Basil Fried Rice', category: 'Rice', price: 12.5, spicy: true },
    { name: 'Mango Sticky Rice', category: 'Desserts', price: 7.9, veg: true, vegan: true },
    { name: 'Thai Iced Tea', category: 'Drinks', price: 4.5, veg: true },
  ],
  vietnamese: [
    { name: 'Beef Pho', category: 'Popular', price: 13.9 },
    { name: 'Vegetable Pho', category: 'Popular', price: 12.5, veg: true, vegan: true },
    { name: 'Banh Mi', category: 'Starters', price: 8.9 },
    { name: 'Fresh Spring Rolls', category: 'Starters', price: 7.5, veg: true },
    { name: 'Vietnamese Iced Coffee', category: 'Drinks', price: 4.9, veg: true },
    { name: 'Broken Rice Plate', category: 'Rice', price: 13.5 },
  ],
  italian: [
    { name: 'Margherita Pizza', category: 'Popular', price: 18.9, veg: true },
    { name: 'Spaghetti Carbonara', category: 'Main Course', price: 17.9 },
    { name: 'Penne Arrabbiata', category: 'Main Course', price: 15.9, veg: true, spicy: true },
    { name: 'Bruschetta', category: 'Starters', price: 9.9, veg: true },
    { name: 'Caprese Salad', category: 'Starters', price: 11.9, veg: true },
    { name: 'Tiramisu', category: 'Desserts', price: 8.9, veg: true },
    { name: 'House Red Wine', category: 'Drinks', price: 9.5, veg: true, vegan: true },
  ],
  mexican: [
    { name: 'Chicken Tacos (3pc)', category: 'Popular', price: 13.9 },
    { name: 'Beef Burrito', category: 'Main Course', price: 15.9 },
    { name: 'Vegetable Quesadilla', category: 'Main Course', price: 13.5, veg: true },
    { name: 'Guacamole & Chips', category: 'Starters', price: 8.9, veg: true, vegan: true },
    { name: 'Churros', category: 'Desserts', price: 6.9, veg: true },
    { name: 'Horchata', category: 'Drinks', price: 4.5, veg: true },
  ],
  american: [
    { name: 'Classic Cheeseburger', category: 'Popular', price: 16.9 },
    { name: 'BBQ Ribs', category: 'Main Course', price: 24.9 },
    { name: 'Buffalo Wings (6pc)', category: 'Starters', price: 11.9, spicy: true },
    { name: 'Mac and Cheese', category: 'Main Course', price: 12.9, veg: true },
    { name: 'Loaded Fries', category: 'Starters', price: 9.9, veg: true },
    { name: 'Milkshake', category: 'Drinks', price: 6.9, veg: true },
    { name: 'New York Cheesecake', category: 'Desserts', price: 8.5, veg: true },
  ],
  mediterranean: [
    { name: 'Chicken Shawarma Plate', category: 'Popular', price: 15.9 },
    { name: 'Falafel Wrap', category: 'Main Course', price: 11.9, veg: true, vegan: true },
    { name: 'Hummus & Pita', category: 'Starters', price: 8.9, veg: true, vegan: true },
    { name: 'Greek Salad', category: 'Starters', price: 10.9, veg: true },
    { name: 'Grilled Halloumi', category: 'Main Course', price: 13.9, veg: true },
    { name: 'Baklava', category: 'Desserts', price: 6.5, veg: true },
  ],
  arabic: [
    { name: 'Lamb Kebab Platter', category: 'Popular', price: 19.9 },
    { name: 'Chicken Mandi', category: 'Rice', price: 17.9 },
    { name: 'Kibbeh', category: 'Starters', price: 9.9 },
    { name: 'Tabbouleh', category: 'Starters', price: 8.9, veg: true, vegan: true },
    { name: 'Arabic Coffee', category: 'Drinks', price: 4.5, veg: true, vegan: true },
    { name: 'Kunafa', category: 'Desserts', price: 7.9, veg: true },
  ],
  singaporean: [
    { name: 'Chicken Rice', category: 'Popular', price: 6.9 },
    { name: 'Laksa', category: 'Popular', price: 8.9, spicy: true },
    { name: 'Char Kway Teow', category: 'Main Course', price: 8.5 },
    { name: 'Chilli Crab', category: 'Main Course', price: 42.0, spicy: true },
    { name: 'Satay (6 sticks)', category: 'Starters', price: 9.9 },
    { name: 'Kaya Toast Set', category: 'Popular', price: 6.5, veg: true },
    { name: 'Teh Tarik', category: 'Drinks', price: 2.5, veg: true },
  ],
  malaysian: [
    { name: 'Nasi Lemak', category: 'Popular', price: 9.9, spicy: true },
    { name: 'Beef Rendang', category: 'Main Course', price: 16.9, spicy: true },
    { name: 'Roti Canai', category: 'Bread', price: 3.5, veg: true },
    { name: 'Mee Goreng', category: 'Main Course', price: 8.9 },
    { name: 'Cendol', category: 'Desserts', price: 5.9, veg: true },
    { name: 'Sirap Bandung', category: 'Drinks', price: 3.5, veg: true },
  ],
  fusion: [
    { name: 'Truffle Fried Rice', category: 'Popular', price: 18.9, veg: true },
    { name: 'Miso Butter Pasta', category: 'Main Course', price: 19.9, veg: true },
    { name: 'Kimchi Quesadilla', category: 'Starters', price: 12.9, veg: true, spicy: true },
    { name: 'Salted Egg Chicken Burger', category: 'Popular', price: 16.9 },
    { name: 'Yuzu Cheesecake', category: 'Desserts', price: 9.5, veg: true },
  ],
  pizza: [
    { name: 'Pepperoni Pizza', category: 'Popular', price: 19.9 },
    { name: 'Four Cheese Pizza', category: 'Popular', price: 20.9, veg: true },
    { name: 'Garlic Bread', category: 'Starters', price: 6.9, veg: true },
    { name: 'Caesar Salad', category: 'Starters', price: 10.9 },
    { name: 'Tiramisu', category: 'Desserts', price: 8.9, veg: true },
  ],
  burger: [
    { name: 'Signature Beef Burger', category: 'Popular', price: 15.9 },
    { name: 'Crispy Chicken Burger', category: 'Popular', price: 14.9 },
    { name: 'Plant-Based Burger', category: 'Popular', price: 15.9, veg: true, vegan: true },
    { name: 'Curly Fries', category: 'Starters', price: 6.9, veg: true, vegan: true },
    { name: 'Chocolate Shake', category: 'Drinks', price: 6.9, veg: true },
  ],
  cafe: [
    { name: 'Flat White', category: 'Drinks', price: 5.9, veg: true },
    { name: 'Avocado Toast', category: 'Popular', price: 13.9, veg: true },
    { name: 'Eggs Benedict', category: 'Popular', price: 15.9 },
    { name: 'Granola Bowl', category: 'Popular', price: 11.9, veg: true, vegan: true },
    { name: 'Blueberry Muffin', category: 'Desserts', price: 4.9, veg: true },
  ],
  dessert: [
    { name: 'Molten Chocolate Cake', category: 'Popular', price: 9.9, veg: true },
    { name: 'Croissant', category: 'Popular', price: 4.5, veg: true },
    { name: 'Macarons (6pc)', category: 'Popular', price: 14.9, veg: true },
    { name: 'Soft Serve Ice Cream', category: 'Popular', price: 5.9, veg: true },
    { name: 'Iced Latte', category: 'Drinks', price: 6.5, veg: true },
  ],
};

export const REVIEW_TEMPLATES: { title: string; comment: string; ratingWeight: 1 | 2 | 3 | 4 | 5 }[] = [
  { title: 'Absolutely loved it', comment: 'Great food and the portions were large. Friendly staff too, will come back.', ratingWeight: 5 },
  { title: 'Solid choice', comment: 'Good value for money and fresh ingredients. Friendly service made it better.', ratingWeight: 4 },
  { title: 'Great atmosphere', comment: 'Cozy spot with a great atmosphere, perfect for a weeknight dinner. Great food overall.', ratingWeight: 5 },
  { title: 'Pretty good', comment: 'Tasty food, reasonably priced. Nothing fancy but does the job well.', ratingWeight: 4 },
  { title: 'Long wait but worth it', comment: 'Food was great but there was a long wait during weekends. Portions were generous though.', ratingWeight: 4 },
  { title: 'A bit noisy', comment: 'Can get noisy during peak hours, but the food quality makes up for it.', ratingWeight: 3 },
  { title: 'Disappointing visit', comment: 'Food arrived cold and service was slow. Expected more given the reviews.', ratingWeight: 2 },
  { title: 'Overpriced for what it is', comment: 'It was okay but felt overpriced for the portion size. Friendly staff at least.', ratingWeight: 3 },
  { title: 'Amazing flavors', comment: 'Every dish we ordered was delicious. Large portions and fresh ingredients throughout.', ratingWeight: 5 },
  { title: 'Would recommend', comment: 'Friendly service, good value, and tasty food. A reliable neighborhood spot.', ratingWeight: 4 },
  { title: 'Just average', comment: 'Nothing stood out, food was fine but not memorable. Service was okay.', ratingWeight: 3 },
  { title: 'Not what I expected', comment: 'Small portions and it took a while to get served. Probably won\'t return.', ratingWeight: 2 },
];
